apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.deployment.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.label }}
    spec:
      containers:
      - name: {{ .Values.frontend.container.name }}
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.container.port }}
        env:
        - name: VITE_API_BASE_URL
          value: ""
