apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: default
spec:
  endpoints:
    - interval: 10s
      path: /actuator/prometheus
      scrapeTimeout: 9s
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/part-of: backend-service